server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Headers for Godot 4
    add_header Cross-Origin-Opener-Policy "same-origin";
    add_header Cross-Origin-Embedder-Policy "require-corp";
    add_header Cache-Control "no-cache, no-store, must-revalidate";

    # Include MIME types
    include /etc/nginx/mime.types;
    types {
        application/wasm wasm;
        application/octet-stream pck;
    }


    location / {
        try_files $uri $uri/ /index.html;
    }
}
